name: List open user PRs
on:
  pull_request:
    types:
      - opened
      - reopened
jobs:
  list-prs:
    name: List open user PRs
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AUTHOR: ${{ github.event.pull_request.user.id }}
      PR_NUMBER: ${{ github.event.number }}
      REPO: ${{ github.repository }}
    steps:
      - run: |
          LIST=$(gh pr ls -A $AUTHOR -R $REPO)
          COMMENT_BODY=$(cat <<EOF
          Current PR list for @$AUTHOR:
          \`\`\`
          $LIST
          \`\`\`
          EOF
          )

          gh pr comment $PR_NUMBER -R $REPO -b '$COMMENT_BODY'
