name: Auto fill preview commits
run-name: Auto fill PR body with commits by ${{ github.actor }}

on:
  pull_request:
    types: [opened, reopened]

jobs:
  auto-fill-pr-body-with-commits:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fill PR body
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo $(git log --oneline) >> commits.txt
          gh pr comment $PR_NUMBER -f ./commits.txt
